### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by jt888666** [ORIE4741/ProjectsFall2019#101]
The project is about cryptocurrency bitcoin. Although the cryptocurrency bitcoin posed great opportunities for policymakers, economists and consumers, the price formation of it cannot be explained by standard economic theories since several factors that formed the basis of currency price are absent. They retrieved data of bitcoin pricing over the past seven years on the website of CoinMarketCap. They also used data of US monthly inflation rate from US Inflation Calculator, gold prices from goldprice.org and daily stock data of GPU producer from Google Finance. This project is tended to predict price movement of bitcoin with available data and several factors including gold price, inflation rate and GPU pricing. 

Good things:
The first thing I like about the proposal is that the topic is really interesting. The second thing is that they considered a lot of factors that may influence the price movement of bitcoin. I also like the objective of their proposal, which is to figure out the metrics that correlated to bitcoin price. 

Improvements:
The three areas for improvements are that they could include additional factors that may influence the price of Bitcoin. Since Bitcoin reward halving is a contributor of the fluctuating price of cryptocurrency, it has a significant impact on the mining industry. I would also suggest to consider new technological changes to Bitcoin. It is also a good idea to consider the media influence on the price of Bitcoin.

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.
