### ISSUE TITLE
Peer Review -- Hospital Analysis

### ISSUE THREAD

**Issue by sl2687** [ORIE4741/ProjectsFall2019#104]
The authors proposed a method to choose the most appropriate hospital for patients. They are primarily using the data provided by Statewide Planning and Research Cooperative System, and other Kaggle data, to facilitate the decision process. The goal of the proposal is to make the hospital selection process easier for patients.

Things I like:
1.  The project will benefit patients, which can have a great impact to the society.
2. The questions are raised from different point of views.
3. The data set is trustful and large.

Potential improvements:
1. It might be good to show how to connect the input of the model to the labels that are used for training.
2. Perhaps mention the application range of the model (e.g. patients in the entire world, within US, or within NY, etc)
3. It can be good to see if there are any incompatibilities to combine data from different sources.

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.
