### ISSUE TITLE
Peer Review -- Lending rate prediction

### ISSUE THREAD

**Issue by sl2687** [ORIE4741/ProjectsFall2019#106]
The authors proposed a method to price the loan. They are primarily using the data provided by All Lending Club Loan Data from Kaggle, and the Bureau of Labor Statistics and the Federal Reserve of Economic Data, to facilitate the calculation. The goal of the proposal is to set a good interest rate for a given loan and determine the best price in order to make profit.

Things I like:
1. The project will judge the best loan rate, which helps to maintain a healthy economic environment.
2. The questions are critical.
3. The data set includes lots of information.

Potential improvements:
1. It might be good to show how to connect the input of the model to the labels that are used for training.
2. It might be good to explain why the focus is only on the file for accepted loans (i.e. why rejected loans are ignored?)
3. It is helpful to explain how to use the geographic data and Fed Economic Data, as the URL only links to the homepage, not the actual data set.

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.
