### ISSUE TITLE
Peer review by zl722

### ISSUE THREAD

**Issue by zliu374** [ORIE4741/ProjectsFall2019#108]
The project seeks to find the reasons behind employees turnovers. The data is "HR Analytics Case Study" from Kaggle.com. The project is very meaningful and useful, since employers can use the result to provide better working environment for employees, and thus reducing turnover rates.

Likes:
1. The project discusses a contemporary problem, which concerns many millennials like us.
2. There are multiple tables with multiple different columns, which makes this project interesting. There are many factors/variables that can be worked on.

Improvements:
1. Employees may leave current companies for different reasons(dislike of current company, better opportunity elsewhere). What do their turnovers indicate?

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.
