### ISSUE TITLE
Peer review by sr2232

### ISSUE THREAD

**Issue by silviaruiz44** [ORIE4741/ProjectsFall2019#109]
[Trip Advisor.docx](https://github.com/ORIE4741/ProjectsFall2019/files/3700395/Trip.Advisor.docx)

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.

**Comment by silviaruiz44** [comment]
Got you. Thank you for the clarification
