### ISSUE TITLE
Peer review from Yishu Zhang

### ISSUE THREAD

**Issue by yishuzhang0302** [ORIE4741/ProjectsFall2019#111]
This project is about predicting stock price in market. Since the concern for market growth is expanding in US now, the prediction focuses on stock price prediction in bear market. The data they are using is S&P 500 company historical prices with fundamental data from Kaggle. Their objective is to create an machine learning model that can predict stock prices with relatively high accuracy.

Three points I like about this project

When I look at recent market news, I also notice issues like the inverted yield curve (which is a historical sign for recession) and decreased interest rate (to booster economy). So this is quite a meaningful and insightful project, which tries to find the pattern and predict potential stock prices in bear market.
The data source from Kaggle is quite authoritative and it not only contains prices but also company information.
They not only care about accuracy but also complexity of the algorithms.
Three points I do not like about this project

The objective of the project is fabulous, but the scope looks a bit large for me. Predicting stock prices is something many people attempted to do historically with complicated math/economic models.
The definition of ‘bear market’ is not quite clear. Also does it mean that we do not want to check data in ‘bull market’ that much?
For the proposed algorithms, from my understanding, they are mostly dealing with classification problem instead of regression ones (maybe there are some part of the applications of algorithms I do not quite familiar).

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.
