### ISSUE TITLE
Midterm Peer Review

### ISSUE THREAD

**Issue by wenjia-z** [ORIE4741/ProjectsFall2019#117]
This project aims to build a model to predict the rating score and number of reviewers of the movie using the related movie information like the production company, the budget, etc. In this midterm report, they mainly discuss the content of their dataset, their way of doing featuring engineering and target processing, the results of linear regression, and their future plan.

Things I like:
1.	They use the IMDB’s weighted rating formula to process the target and filter the movies that have fewer votes than at least 95% of the movies on the list. 
2.	The way they form the linear model is quite informative and reasonable. They first test every single feature and make a baseline of their research, and then shape some features with cubic transformation and do a “pseudo-polynomial fitting” to improve the model. 
3.	They compare different models they have tried and plot the test error. Using plots is a good way to show and tell.

Things I think they can improve:
1.	When they are describing the “messy” characteristic of their data, I think it would be better to use plots/charts with exact numbers instead of saying “Three of the 24 columns have more than 50% of the data is missing”. Also, it would be better to show some statistical analysis results in this part, to help others know better about the dataset.
2.	In the feature preprocessing part, I’m not sure why they chose to use Boolean encoding to process “Budget” and “Runtime”, I think they do not provide a valid reason why this is better than just using the true number of the data. And it would also be better to provide some rationale about why replacing the missing value with zero, instead of dropping it.
3.	As they mentioned, they split the data into train-validation-test set, I think it would be better if they could show separately how the models perform in different sets. Also, I think they should provide more analysis of the outliers in Model II and III parts.

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.

**Comment by wenjia-z** [comment]
Sorry I made a mistake, could you please help me delete this issue? Thank you very much.

**Comment by wenjia-z** [comment]
Sorry I made a mistake, could you please help me delete this issue? Thank you very much.

**Comment by sijiafan** [comment]
Wenjia, don't worry. I will close this.
