### ISSUE TITLE
Midterm Review

### ISSUE THREAD

**Issue by bjk99** [ORIE4741/ProjectsFall2019#120]
Your group did a lot of meaningful work, but it is unfortunate that you haven't found a regression that matches your data yet. You may want to try models other than linear regression at this point. I do like that you shared some of the different attempts, but I wish you had described the specific data manipulations made to get from one model to the next. When you get to the final report, it may not be necessary to include all of these attempts, but it is useful here to show the work you have been doing.

Also, your report is well structured, but contains a few grammatical/spelling errors, so definitely check for that before submitting the final report.

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.
