### ISSUE TITLE
midterm peer review

### ISSUE THREAD

**Issue by ghost** [ORIE4741/ProjectsFall2019#123]
Rl paper
This project focuses on using neural nets and reinforcement learning on solving minimum spanning trees of 10 nodes and analyzing how this method compares to traditional algorithms such as Prims and Kruskals. The team generated a million fully connected graphs and altered existing code that uses GNN to find feasible TSP solutions to work for MST problems. They found that their methods produced the true MST 14 percent of the time.

Things I liked:
I liked how the team altered and existing package to work for their project. Switching the application from TSP approximation to MST approximation seems interesting.
Good explanation of what a minimum spanning tree is and what other methods can be used to find a solution.
I liked that the design of experiment was described very clearly

Improvement:
The paper mentioned that the experiment was tested on graphs with 10 nodes, wouldn’t the size of the graph be small enough to solve via prims or Kruskals algorithm with 100 percent accuracy? What are the advantages of using GNN to solve MST problems, is it useful for more complex graphs?
Perhaps include more descriptions of what convolutional GNN and beam search do/ what they are. I’m familiar with MST/TSP etc but don’t have much background on deep learning so it would be interested to learn.

Perhaps dig deeper in the 14 percent accuracy metric of your experiment, is there any value in approximate MSTs? If so maybe your accuracy is higher?

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.

**Comment by ghost** [comment]
sorry about that!
