### ISSUE TITLE
Midterm Peer Review_jl3947

### ISSUE THREAD

**Issue by jiahuilu97** [ORIE4741/ProjectsFall2019#124]
This project is mainly about predicting airline customers satisfaction and preference. The dataset is from Skytrax website, including the comment and corresponding traveler types. 

### Likes
1. They describe the dataset thoroughly. They described every feature and using some plot to show the distribution of overall rating and the percentage of recommendation.
2. They found out the abnormal due to the amount of reviews for some airlines and provide to solution to this problem.
3. They plan to improve their model with more features including text features. And they also plan to use a classification model about recommendation. This will make the report more reliable.

### Suggestions
1. Using feature engineering to select some feature into the model instead of using all features.
2. Providing an abstract to declare your project’s proposal.
3. All the links of dataset and plots are not working.

Hope you can succeed in this project!

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.

**Comment by jiahuilu97** [comment]
Oh sorry. Thanks for reminding me!
