### ISSUE TITLE
Project proposal - peer review assignment_ky392

### ISSUE THREAD

**Issue by huaiyoubuyi** [ORIE4741/ProjectsFall2019#92]
This project is about hotel Airbnb prices. It aims at examining factors affecting the airbnb prices. It is using data from Kaggle open dataset listing.

It is a good area to explore for the large number of tourists in the world. Also, the introduction of factors is innovative. Finally, the dataset is of high quality and worth researching. However, the proposal is too brief to show the detailed methods and feasibility. Also, two other groups are doing the similar thing and it  is worth thinking how to get distinguished with innovation. Finally, I do not think using correlation is enough to explain all the factors. But if other methods are used perfectly, that would be fantastic! Keep calm and carry on!

**Comment by sijiafan** [comment]
please leave your peer review comment on the group project's repo, but not on this ProjectsFall2019 repo.
